export type Testament = 'old' | 'new'

export type BookDefinition = {
  id: number
  english: string
  testament: Testament
}

export const BOOK_DEFINITIONS: BookDefinition[] = [
  { id: 1, english: 'Genesis', testament: 'old' },
  { id: 2, english: 'Exodus', testament: 'old' },
  { id: 3, english: 'Leviticus', testament: 'old' },
  { id: 4, english: 'Numbers', testament: 'old' },
  { id: 5, english: 'Deuteronomy', testament: 'old' },
  { id: 6, english: 'Joshua', testament: 'old' },
  { id: 7, english: 'Judges', testament: 'old' },
  { id: 8, english: 'Ruth', testament: 'old' },
  { id: 9, english: '1 Samuel', testament: 'old' },
  { id: 10, english: '2 Samuel', testament: 'old' },
  { id: 11, english: '1 Kings', testament: 'old' },
  { id: 12, english: '2 Kings', testament: 'old' },
  { id: 13, english: '1 Chronicles', testament: 'old' },
  { id: 14, english: '2 Chronicles', testament: 'old' },
  { id: 15, english: 'Ezra', testament: 'old' },
  { id: 16, english: 'Nehemiah', testament: 'old' },
  { id: 17, english: 'Esther', testament: 'old' },
  { id: 18, english: 'Job', testament: 'old' },
  { id: 19, english: 'Psalms', testament: 'old' },
  { id: 20, english: 'Proverbs', testament: 'old' },
  { id: 21, english: 'Ecclesiastes', testament: 'old' },
  { id: 22, english: 'Song of Solomon', testament: 'old' },
  { id: 23, english: 'Isaiah', testament: 'old' },
  { id: 24, english: 'Jeremiah', testament: 'old' },
  { id: 25, english: 'Lamentations', testament: 'old' },
  { id: 26, english: 'Ezekiel', testament: 'old' },
  { id: 27, english: 'Daniel', testament: 'old' },
  { id: 28, english: 'Hosea', testament: 'old' },
  { id: 29, english: 'Joel', testament: 'old' },
  { id: 30, english: 'Amos', testament: 'old' },
  { id: 31, english: 'Obadiah', testament: 'old' },
  { id: 32, english: 'Jonah', testament: 'old' },
  { id: 33, english: 'Micah', testament: 'old' },
  { id: 34, english: 'Nahum', testament: 'old' },
  { id: 35, english: 'Habakkuk', testament: 'old' },
  { id: 36, english: 'Zephaniah', testament: 'old' },
  { id: 37, english: 'Haggai', testament: 'old' },
  { id: 38, english: 'Zechariah', testament: 'old' },
  { id: 39, english: 'Malachi', testament: 'old' },
  { id: 40, english: 'Matthew', testament: 'new' },
  { id: 41, english: 'Mark', testament: 'new' },
  { id: 42, english: 'Luke', testament: 'new' },
  { id: 43, english: 'John', testament: 'new' },
  { id: 44, english: 'Acts', testament: 'new' },
  { id: 45, english: 'Romans', testament: 'new' },
  { id: 46, english: '1 Corinthians', testament: 'new' },
  { id: 47, english: '2 Corinthians', testament: 'new' },
  { id: 48, english: 'Galatians', testament: 'new' },
  { id: 49, english: 'Ephesians', testament: 'new' },
  { id: 50, english: 'Philippians', testament: 'new' },
  { id: 51, english: 'Colossians', testament: 'new' },
  { id: 52, english: '1 Thessalonians', testament: 'new' },
  { id: 53, english: '2 Thessalonians', testament: 'new' },
  { id: 54, english: '1 Timothy', testament: 'new' },
  { id: 55, english: '2 Timothy', testament: 'new' },
  { id: 56, english: 'Titus', testament: 'new' },
  { id: 57, english: 'Philemon', testament: 'new' },
  { id: 58, english: 'Hebrews', testament: 'new' },
  { id: 59, english: 'James', testament: 'new' },
  { id: 60, english: '1 Peter', testament: 'new' },
  { id: 61, english: '2 Peter', testament: 'new' },
  { id: 62, english: '1 John', testament: 'new' },
  { id: 63, english: '2 John', testament: 'new' },
  { id: 64, english: '3 John', testament: 'new' },
  { id: 65, english: 'Jude', testament: 'new' },
  { id: 66, english: 'Revelation', testament: 'new' },
]
